### ISSUE TITLE
Loading Config error

### ISSUE THREAD

**Issue by xMikux** [CoolDCB/VoidWarp-Limbo#1] opened 2023-02-10 16:25 UTC
When I install the plugins, it throws up the error https://pastebin.com/Y6zukiMW

Seem like \\\config.yml problem.

**Comment by OakLoaf** [comment] 2023-02-10 16:27
Hmm looks like the config isn't being created correctly, let me try to reproduce this.

**Comment by xMikux** [comment] 2023-02-10 16:28
It create correctly, but can't load.

**Comment by xMikux** [comment] 2023-02-10 16:29
![image](https://user-images.githubusercontent.com/26039249/218144259-6575fcb5-3745-45ae-bfc2-bede16a61f69.png)

**Comment by OakLoaf** [comment] 2023-02-10 16:29
Oh.. I put the wrong slash..

**Comment by OakLoaf** [comment] 2023-02-10 16:30
Wonder why it was working on my local limbo

**Comment by xMikux** [comment] 2023-02-10 16:30
I think because windows

**Comment by xMikux** [comment] 2023-02-10 16:30
windows path all is \\, so no error
but linux not

**Comment by OakLoaf** [comment] 2023-02-10 16:30
> I think because windows

Ahh yes, most likely. I'll post a fix for this as soon as I am on my PC!

**Comment by OakLoaf** [comment] 2023-02-10 17:10
This issue has been fixed in release [1.0.3](https://github.com/CoolDCB/VoidWarp-Limbo/releases/tag/1.0.3)

**Closed as completed** 2023-02-10 17:10 UTC
